### ISSUE TITLE
Access Model Variants

### ISSUE THREAD

**Issue by xiaoyuxin1002** [yingweima2022/CodeLLM#2]
Hi, thanks for the great work and open-sourcing the model weights!
As I am planning to use your model variants for my research, I am having trouble figuring out where I can find NN (2.6B), NC (2.6B), CC (2.6B).
In particular, the shared link to CodePanGu2.6B in your readme.md contains 16 checkpoints. I am wondering if I should use filerted_15.ckpt as CODE (2.6B) and if any of them refers to NN (2.6B), NC (2.6B), or CC (2.6B).
In addition, it would be great if there could be a hugging face link for easier setup.

**Comment by yingweima2022** [comment]
Hi, thanks for your attention.

About ```the shared link to CodePanGu2.6B in your readme.md contains 16 checkpoints```
- We have divided CodePanGu2.6B into 16 checkpoints, which you can load together using the mindspore api.
- For NL2.6B, you can download it from the following link, https://openi.pcl.ac.cn/PCL-Platform.Intelligence/PanGu-Alpha?lang=en-US.

About the fine-tuned model, we have no plans to open source it for the time being. But you can access other types of fine-tuned models at https://openi.pcl.ac.cn/PCL-Platform.Intelligence.
